openapi: 3.0.2
info:
  title: Arbeidsoppfolging API
  version: '1.0'
servers:
  - url: https://veilarbapi.dev.intern.nav.no
    description: dev
  - url: https://veilarbapi.intern.nav.no
    description: prod
#  - url: https://veilarbapi.dev.intern.nav.no
#    description: manuell testing only

security:
  - bearerAuth:
    - read

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only
  schemas:
    AktivitetStatus:
      type: string
      enum:
        - PLANLAGT
        - GJENNOMFORES
        - FULLFORT
        - BRUKER_ER_INTERESSERT
        - AVBRUTT
      example: FULLFORT
    AktivitetType:
      enum:
        - Sokeavtale
        - Behandling
        - Mote
        - Samtalereferat
        - StillingFraNav
        - Egenaktivitet
    Baseaktivitet:
      type: object
      required:
        - aktivitet_type_navn
        - aktivitet_type
      discriminator:
        propertyName: aktivitet_type
#        mapping:
#          Sokeavtale: '#/components/schemas/Sokeavtale'
#          Behandling: '#/components/schemas/Behandling'
#          Mote: '#/components/schemas/Mote'
#          Samtalereferat: '#/components/schemas/Samtalereferat'
#          StillingFraNav: '#/components/schemas/StillingFraNav'
#          Egenaktivitet: '#/components/schemas/Egenaktivitet'
      properties:
        aktivitet_type:
          type: string
        aktivitet_type_navn:
          type: string
          example: Stilling fra NAV
        avtalt_med_nav:
          type: boolean
          description: Definer om den definerte aktiviteten er avtalt med NAV
          example: true
        status:
          $ref: "#/components/schemas/AktivitetStatus"
        status_navn:
          type: string
        beskrivelse:
          type: string
          description: Beskrivelse av aktiviteten som er planlagt/gjennomført
          example: NAV forventer at du søker omtrent 20 stillinger i denne perioden
        tittel:
          type: string
        fra_dato:
          type: string
          format: date-time
        til_dato:
          type: string
          format: date-time
        opprettet_dato:
          type: string
          format: date-time
        endret_dato:
          type: string
          format: date-time
        dialog:
          $ref: '#/components/schemas/Dialog'
    Sokeavtale:
      required:
        - aktivitet_type
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
#            aktivitet_type:
#              type: string
            antallStillingerIUken:
              type: integer
            avtaleOppfolging:
              type: string
    Behandling:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            behandlingSted:
              type: string
    Mote:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            adresse:
              type: string
            forberedelser:
              type: string
            kanal:
              type: string
              example: Telefonmøte
            referat:
              description: Referatet hvis det er delt med bruker
              type: string
    Samtalereferat:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            kanal:
              type: string
              example: Telefonmøte
            referat:
              type: string
              description: Referatet hvis det er delt med bruker
    Egenaktivitet:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            hensikt:
              type: string
              example: Mål med aktiviteten (fritekst)
            oppfolging:
              type: string
              description: Huskeliste for denne aktiviteten (fritekst)
    StillingFraNav:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            cvKanDelesData:
              type: object
              properties:
                kanDeles:
                  type: boolean
                  description: Samtykke fra bruker om at NAV får lov til å dele deres CV
                endretTidspunkt:
                  type: string
                  format: date-time
                endretAv:
                  type: string
                endretAvType:
                  type: string
                  enum:
                    - BRUKER
                    - NAV
                avtaltDato:
                  type: string
                  format: date
            soknadsfrist:
              type: string
            svarfrist:
              type: string
              format: date
            arbeidsgiver:
              type: string
            bestillingsId:
              type: string
            stillingsId:
              type: string
            arbeidssted:
              type: string
            soknadsstatus:
              type: string
              example: Skal på intervju
    Oppfolgingsperioder:
      type: object
      properties:
        oppfolgingsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Oppfolgingsperiode'
        feil:
          description: Feilende kilde ved ufullstendige data
          type: array
          items:
            type: object
            properties:
              feilkilder:
                description: Hvilken datakilde vi ikke kunne hente data fra
                type: string
                enum:
                  - OPPFOLGING
                  - DIALOG
                  - AKTIVITET
                  - ANNET
              feilmelding:
                description: Feilmelding i klar tekst
                type: string
                example: Kunne ikke hente dialoger.
    Oppfolgingsperiode:
      type: object
      properties:
        startDato:
          type: string
          format: date-time
        sluttDato:
          type: string
          format: date-time
        dialoger:
          description:  Dialoger som ikke hører til en aktivitet
          type: array
          items:
            $ref: '#/components/schemas/Dialog'
        aktiviteter:
          type: array
          items:
            $ref: '#/components/schemas/Baseaktivitet'
          description: Liste med aktiviteter tilknyttet en oppfølgingsperiode
    AktivitetUnion:
      type: object
      oneOf:
        - $ref: '#/components/schemas/Sokeavtale'
        - $ref: '#/components/schemas/Behandling'
        - $ref: '#/components/schemas/Mote'
        - $ref: '#/components/schemas/Samtalereferat'
        - $ref: '#/components/schemas/StillingFraNav'
        - $ref: '#/components/schemas/Egenaktivitet'
#      discriminator:
#        propertyName: aktivitet_type
#        mapping:
#          Sokeavtale: '#/components/schemas/Sokeavtale'
#          Behandling: '#/components/schemas/Behandling'
#          Mote: '#/components/schemas/Mote'
#          Samtalereferat: '#/components/schemas/Samtalereferat'
#          StillingFraNav: '#/components/schemas/StillingFraNav'
#          Egenaktivitet: '#/components/schemas/Egenaktivitet'

    Melding:
      type: object
      properties:
        avsenderType:
          type: string
          enum:
            - NAV
            - BRUKER
        sendt_dato:
          type: string
          format: date-time
          description: Beskriver når meldingen ble sendt til/fra NAV
          example: 2022-02-21T08:00:00+02:00
        lest:
          type: boolean
          description: Beskriver om melding er lest av bruker/veileder
          example: true
        meldingstekst:
          type: string
          description: Fritekstfelt med melding som ble sendt/opprettet
          example: Lorem ipsum..
    Dialog:
      type: object
      properties:
        dialog_start:
          type: string
          format: date-time
          description: Beskriver når dialogen med NAV startet.
          example: 2022-02-21T08:00:00+02:00
        tittel:
          type: string
          description: Beskrivende navn på dialogen/tråden
          example: 'Stilling fra NAV: Servitør'
        ventersvarnav:
          type: boolean
          description: Beskriver om dialogen er tagget for at den venter på svar fra NAV
          example: true
        ventersvarbruker:
          type: boolean
          description: Beskriver om dialogen er tagget for at den venter på svar fra bruker
          example: false
        meldinger:
          type: array
          items:
            $ref: '#/components/schemas/Melding'
    Oppfolgingsinfo:
      type: object
      properties:
        OppfolgingsEnhet:
          type: object
          description: Nav enhet med oppfølgingsansvar for bruker
          properties:
            enhetId:
              type: string
              example: 1234
            navn:
              type: string
              example: NAV hamar
        underOppfolging:
          type: boolean
          description: Definerer om brukeren er under arbeidsrettet oppfølging eller ikke
          example: true
        primaerVeileder:
          type: string
          description: NAV ident til brukerens veileder for oppfølgingen
          example: Z999999
        feil:
          description: Feilende kilde ved ufullstendige data
          type: array
          items:
            type: object
            properties:
              feilkilder:
                description: Hvilken datakilde vi ikke kunne hente data fra
                type: string
              feilmelding:
                description: Feilmelding i klar tekst
                type: string
                example: Kunne ikke hente primærveileder

paths:
  /v1/oppfolging/periode:
    get:
      operationId: hentOppfolgingsperioder
      description: ''
      parameters:
        - name: aktorId
          in: query
          required: true
          schema:
            type: string
          description: AktørID til personen man ønsker å hente ut aktivitetsplanen til
        - name: Nav-Consumer-Id
          in: header
          required: true
          schema:
            type: string
        - name: Nav-Call-Id
          in: header
          required: true
          schema:
            type: string
      responses:
#  TODO andre returkoder
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Oppfolgingsperioder'
  /v1/oppfolging/info:
    get:
      description: Returnerer grunnleggende informasjon om arbeidsrettet oppfølging for brukeren, og hvorvidt brukeren er under oppfølging
      parameters:
        - name: aktorId
          in: query
          required: true
          schema:
            type: string
          description: AktørID til personen man ønsker å hente ut oppølgingsinfo for
        - name: Nav-Consumer-Id
          in: header
          required: true
          schema:
            type: string
        - name: Nav-Call-Id
          in: header
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Oppfolgingsinfo'
