openapi: 3.0.2
info:
  title: Arbeidsoppfolging API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
components:
  schemas:
    Baseaktivitet:
      type: object
      required:
        - aktivitet_type
        - aktivitet_id
      discriminator:
        propertyName: aktivitet_type
      properties:
        aktivitet_id:
          type: number
          format: int64
        aktivitet_type:
          type: string
          example: Samtalereferat
        kontorsperre_enhet_id:
          type: string
        avtalt_med_nav:
          type: boolean
          description: Definer om den definerte aktiviteten er avtalt med NAV
          example: true
        status:
          type: string
          enum:
            - PLANLAGT
            - GJENNOMFORES
            - FULLFORT
            - BRUKER_ER_INTERESSERT
            - AVBRUTT
          example: FULLFORT
        beskrivelse:
          type: string
          description: Beskrivelse av aktiviteten som er planlagt/gjennomført
          example: NAV forventer at du søker omtrent 20 stillinger i denne perioden
        tittel:
          type: string
        fra_dato:
          type: string
          format: date-time
        til_dato:
          type: string
          format: date-time
        opprettet_dato:
          type: string
          format: date-time
        endret_dato:
          type: string
          format: date-time
    Egenaktivitet:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            hensikt:
              type: string
            oppfolging:
              type: string
    Jobbsoeking:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            arbeidsgiver:
              type: string
            stillingsTittel:
              type: string
            arbeidssted:
              type: string
            stillingsoekEtikett:
              type: string
              enum:
                - SOKNAD_SENDT
                - INNKALT_TIL_INTERVJU
                - AVSLAG
                - JOBBTILBUD
            kontaktPerson:
              type: string
    Sokeavtale:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            antallStillingerSokes:
              type: integer
            antallStillingerIUken:
              type: integer
            avtaleOppfolging:
              type: string
    Ijobb:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            jobbStatusType:
              type: string
              enum:
                - HELTID
                - DELTID
            ansettelsesforhold:
              type: string
            arbeidstid:
              type: string
    Behandling:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            behandlingType:
              type: string
            behandlingSted:
              type: string
            effekt:
              type: string
            behandlingOppfolging:
              type: string
    Mote:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            adresse:
              type: string
            forberedelser:
              type: string
            kanal:
              type: string
              enum:
                - OPPMOTE
                - TELEFON
                - INTERNETT
            referat:
              type: string
            referatPublisert:
              type: boolean
    Samtalereferat:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            kanal:
              type: string
              enum:
                - OPPMOTE
                - TELEFON
                - INTERNETT
            referat:
              type: string
            referatPublisert:
              type: boolean
    Stilling_fra_nav:
      allOf:
        - $ref: '#/components/schemas/Baseaktivitet'
        - type: object
          properties:
            cvKanDelesData:
              type: object
              properties:
                kanDeles:
                  type: boolean
                endretTidspunkt:
                  type: string
                  format: date-time
                endretAv:
                  type: string
                endretAvType:
                  type: string
                  enum:
                    - BRUKER
                    - NAV
                avtaltDato:
                  type: string
                  format: date
            soknadsfrist:
              type: string
            svarfrist:
              type: string
              format: date
            arbeidsgiver:
              type: string
            bestillingsId:
              type: string
            stillingsId:
              type: string
            arbeidssted:
              type: string
            soknadsstatus:
              type: string
              enum:
                - VENTER
                - SKAL_PAA_INTERVJU
                - JOBBTILBUD
                - AVSLAG
    Oppfolgingsperiode:
      type: object
      properties:
        id:
          type: string
          format: uuid
        aktiviteter:
          type: array
          items:
            $ref: '#/components/schemas/Aktivitet'
          description: Liste med aktiviteter tilknyttet en oppfølgingsperiode
    Aktivitet:
      type: object
      oneOf:
        - $ref: '#/components/schemas/Egenaktivitet'
        - $ref: '#/components/schemas/Jobbsoeking'
        - $ref: '#/components/schemas/Sokeavtale'
        - $ref: '#/components/schemas/Ijobb'
        - $ref: '#/components/schemas/Behandling'
        - $ref: '#/components/schemas/Mote'
        - $ref: '#/components/schemas/Samtalereferat'
        - $ref: '#/components/schemas/Stilling_fra_nav'
      discriminator:
        propertyName: aktivitet_type
paths:
  /aktivitetsplan:
    get:
      tags:
        - Oppfolging
      description: ''
      parameters:
        - name: aktorId
          in: query
          required: true
          schema:
            type: string
          description: AktørID til personen man ønsker å hente ut aktivitetsplanen til
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Oppfolgingsperiode'
