kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbapi
  namespace: pto
  cluster: dev-gcp
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbapi/veilarbapi:{{version}}
  ingresses:
    - https://veilarbapi.dev.intern.nav.no
  port: 8080
  prometheus:
    enabled: false
  liveness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 768Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  env:
    - name: AZUREAD_JWKS_URL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/discovery/v2.0/keys