kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbapi
  namespace: pto
  cluster: dev-gcp
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbapi/veilarbapi:{{version}}
  ingresses:
    - https://veilarbapi.dev.intern.nav.no
  port: 8080
  prometheus:
    enabled: false
  liveness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 768Mi
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbaktivitet
        mountPath: /var/run/secrets/nais.io/service_user