kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbapi
  namespace: pto
  cluster: dev-gcp
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbapi/veilarbapi:{{version}}
  ingresses:
    - https://veilarbapi.dev.intern.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  liveness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 768Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: ida
          namespace: traktor
          cluster: prod-fss
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
  env:
    - name: AZUREAD_JWKS_URL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/discovery/v2.0/keys
    - name : VEILARBAKTIVITETAPI_URL
      value: https://poao-gcp-proxy.dev-fss-pub.nais.io/proxy/veilarbaktivitet
    - name : VEILARBDIALOGAPI_URL
      value: https://poao-gcp-proxy.dev-fss-pub.nais.io/proxy/veilarbdialog
    - name : VEILARBOPPFOLGINGAPI_URL
      value: https://poao-gcp-proxy.dev-fss-pub.nais.io/proxy/veilarboppfolging
    - name: POAOGCPPROXY_URL
      value: https://poao-gcp-proxy.dev-fss-pub.nais.io/proxy
    - name: POAOGCPPROXY_CLIENT_ID
      value: 1fbc8405-3eae-4f2f-9af8-7c7ba303cd52