kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbapi
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  liveness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 768Mi
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
        - application: saas-proxy
          namespace: teamcrm
    outbound:
      rules:
        - application: veilarbaktivitet
          namespace: dab
        - application: veilarbdialog
          namespace: dab
        - application: veilarboppfolging
          namespace: poao
      external:
        - host: veilarbaktivitet.prod-fss-pub.nais.io
        - host: veilarboppfolging.prod-fss-pub.nais.io
  env:
    - name: AZURE_APP_WELL_KNOWN_URL
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
    - name: VEILARBAKTIVITETAPI_URL
      value: http://veilarbaktivitet.dab/veilarbaktivitet
    - name: VEILARBAKTIVITETAPI_SCOPE
      value: api://prod-gcp.dab.veilarbaktivitet/.default
    - name : VEILARBDIALOGAPI_URL
      value: http://veilarbdialog.dab/veilarbdialog
    - name : VEILARBOPPFOLGINGAPI_URL
      value: http://veilarboppfolging.poao/veilarboppfolging
    - name: VEILARBOPPFOLGINGAPI_SCOPE
      value: api://prod-gcp.poao.veilarboppfolging/.default
